### ISSUE TITLE
fix synchronization in ResultsCache

### ISSUE THREAD

**Issue by jakob-zwiener** [HPI-Information-Systems/Metanome#13]

**Comment by Dacry** [comment]
part of it might have to do with: https://github.com/HPI-Information-Systems/Metanome/pull/283 - this is fixed by now...

**Comment by Dacry** [comment]
1. do not remove results from cache - but copy them to the frontend 
2. therefore declare pointer on the cache results and move it forward over records that have been reported to the frontend
3. The cache result receiver must write the results to disc, when the execution finished (let receiver know when algorithm is done).
