### ISSUE TITLE
algorithm executions should be run  in a separate thread or process

### ISSUE THREAD

**Issue by jakob-zwiener** [HPI-Information-Systems/Metanome#171]

**Comment by Dacry** [comment]
using akka.io actors

**Comment by Dacry** [comment]
Two adjustments in frontend: 
1. User should be able to configure memory for run 
2. User should be able to terminate process

**Comment by Dacry** [comment]
Backend:
Write relevant parameter information to database in order to execute algorithm

**Comment by Dacry** [comment]
Cached result receiver - in designated process
