### ISSUE TITLE
Test different Browser: Firefox, Internet Explorer, Chrome, ...

### ISSUE THREAD

**Issue by thorsten-papenbrock** [HPI-Information-Systems/Metanome#233]
Metanome runs well in Firefox, but it looks strange in the Internet Explorer. So we need to check the style in different browsers and adjust the frontend if needed.

**Comment by maxifischer** [comment]
Metanome works for me in Firefox and Chrome, but Internet Explorer on Windows has some issues for me. The frontend seems to have some communication issues with the backend when adding or deleting an algorithm and storing results. Nothing happens then, I don't even get an error in the Developer Console, it just loads the same page as before.
