### ISSUE TITLE
DFD Algorithm integration

### ISSUE THREAD

**Issue by thorsten-papenbrock** [HPI-Information-Systems/Metanome#276]
The DFD algorithm written by Patrick Schulze is a DUCC-like FD-discovery algorithm that is not yet integrated into Metanome. Hence, the following tasks need to be done:

- extend the algorithm with a Metanome-konform wrapper that implements all required interfaces
- place the extended algorithm into our algorithm repository and integrate it in the build process of this repository
- test the algorithm in a Metanome instance on some datasets and enshure that the results are equal to the results of e.g. TANE, fdep, etc.

**Comment by Dacry** [comment]
-first version is available in dfdIntegration branch of the algorithms repository 
-it works correctly in Metanome

Todo:
review (maybe sdifferent run modes should be supported?) + integrate in build process
