### ISSUE TITLE
"New algorithm" folder

### ISSUE THREAD

**Issue by averissimo** [HPI-Information-Systems/Metanome#348]
Two things:
1. The folder specified in the help to use when adding new algorithms points to the data folder.
2. The algorithms folder is not included in the release or when compiling using mvn

When wanting to add a new algorithm to test it needs to be placed here WEB-INF/classes/algorithms

the fix for the helper text is here: https://github.com/averissimo/Metanome/commit/6d7dc2174b0c1217ea3ece670d8c201136834c27

I've never worked with maven, so I have no idea how to force creating a folder, but it should be trivial

**Comment by VincentS** [comment]
Tried to create maven directory using work around described https://stackoverflow.com/questions/7909183/how-do-i-include-an-empty-directory-in-a-maven-assembly Further investigation required.

**Comment by VincentS** [comment]
This issue is fixed in the next release :)
