### ISSUE TITLE
Fix packaging of the backend module

### ISSUE THREAD

**Issue by sekruse** [HPI-Information-Systems/Metanome#367]
Currently the build fails because the `backend` module is packaged as `war` while at the same time being referenced by other modules (e.g., `example_sql_profiling_algorithm`) that require `jar` packaging.

A solution might be to have separate modules for the code and packaging (e.g., with a `distro` module). Such an effort could also make it easier to build a "headless" Metanome, that is operated from the command line or used as a library in third-party applications.

**Comment by thorsten-papenbrock** [comment]
Fixed: We now build both jar and war in two separate modules.
