### ISSUE TITLE
Build and Installation Issues [emergency]

### ISSUE THREAD

**Issue by SalemSamah** [HPI-Information-Systems/Metanome#369]
I cant build or get install the #**Metanome** 
Please help by sending Installed Version To my email:  samah.salem.ok@gmail.com
This is snap of what i'v faced in the installation
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:14 min (Wall Clock)
[INFO] Finished at: 2017-02-17T00:49:33+01:00
[INFO] Final Memory: 29M/144M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project f
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :frontend
 @tabergma

**Comment by thorsten-papenbrock** [comment]
Dear Salem,
please check that you have Maven 3.1.0 or later installed (see README.md). Earlier versions of maven cannot deal with the npm dependencies of our project. Also check that the frontend was checked our correctly, i.e., after "git submodule init" and "git submodule update" you find all the frontend code in the frontend folder of the project. If this is all correct and the issue still exists, please post a longer snipped of the build failure. Everything after the first ERROR in the log could help to find the problem. Please also document your operating system, Java version, and Maven version, so we can reproduce your error.
Best,
Thorsten

**Comment by SalemSamah** [comment]
First I would to thank you for replaying, @thorsten-papenbroc

 My _fronted_ folder on the built project:
1. 17/02/2017  02:32    <DIR>          .
2. 17/02/2017  02:32    <DIR>          ..
3. 17/02/2017  01:03                58 .gitignore
4. 17/02/2017  01:03             7 583 pom.xml
5. 17/02/2017  03:29    <DIR>          src
6. 17/02/2017  03:32    <DIR>          target
7. 17/02/2017  01:03    <DIR>          WEB-INF
And this is result of _Unzip_ deployment/target/_deployment-1.1-SNAPSHOT-package_with_tomcat.zip_:
1. - 17/02/2017  03:49    <REP>          .
2. - 17/02/2017  03:49    <REP>          ..
3. - 17/02/2017  03:32    <REP>          backend
4. - 17/02/2017  03:49    <REP>          db
5. - 17/02/2017  03:32    <REP>          frontend
6. - 17/02/2017  01:03               113 run.bat
7. - 17/02/2017  01:03               217 run.sh
8. - 17/02/2017  03:46    <REP>          target
9. - 17/02/2017  03:32        10 199 952 webapp-runner.jar

> Is that mean Metanome Project has been built finally ?!

because after the lunching of the project in http://localhost:8080/ 
its automatically redirect me to http://localhost:8080/#/new  
the issue in this web-page, i have no ability to choose algorithm, & when i load test he respond by:

_Results for file 'WDC_astronomical.csv'
No results found!_ 

Furthermore, my console inspector in chrome browser show some errors .... 

GET http://localhost:8081/api/result-store/count/Unique%20Column%20Combination 400 ()
GET http://localhost:8081/api/result-store/count/Conditional%20Unique%20Column%20Combination 400 ()
.etc...

- **Operating SYS, JAVA version & maven version:** 
- Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
- Maven home: C:\Program Files\Apache\maven
- Java version: 1.8.0_11, vendor: Oracle Corporation
- Java home: C:\Program Files\Java\jdk1.8.0_11\jre
- Default locale: fr_FR, platform encoding: Cp1256
- OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

![snap-s](https://cloud.githubusercontent.com/assets/25830903/23060493/3bae2e16-f4fe-11e6-9cb8-5d7f05307b9f.png)
Sorry for my bad English.

**Comment by thorsten-papenbrock** [comment]
OK, because you could compile the deployment-zip, your build seams to work now. The redirect to http://localhost:8080/#/new is also fine: Here you can setup your profiling runs.

Now to the algorithm selection: Metanome does NOT contain any algorithms by default. That is why you don't see any algorithm in your freshly started Metanome instance. You have to add each profiling algorithm yourself. You can find the algorithms and a description on how to add them here: https://hpi.de/naumann/projects/data-profiling-and-analytics/metanome-data-profiling/algorithms.html 

I am not sure what test you loaded that brought up this result screen, so I cannot really explain it. Maybe it is an algorithm that simply produces no output. Then, the "No results found!" message would be just fine and it is also correct that all the GET-calls deliver no results ;-)

**Comment by SalemSamah** [comment]
Thank you Mr.@thorsten-papenbrock,
i appreciate your help,  
the problem has been solved.

**Comment by Edison0521** [comment]
I cannt build the fronted either,Please help me
my email is zhangvan605@gmail.com
 this is the problems:
[INFO] --- frontend-maven-plugin:1.3:npm (npm install) @ frontend ---
[INFO] Running 'npm install --silent' in C:\Users\Administrator\Desktop\metanome\1\Metanome-master\frontend\src
[ERROR] (node:19828) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[ERROR] (node:19828) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[ERROR] (node:19828) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[ERROR] (node:19828) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[ERROR] (node:19828) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[ERROR] (node:19828) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[ERROR] (node:19828) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[ERROR] (node:19828) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[ERROR] (node:19828) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[ERROR] (node:19828) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[INFO]
[INFO] --- frontend-maven-plugin:1.3:bower (bower install) @ frontend ---
[INFO] Running 'bower install --quiet --force-latest' in C:\Users\Administrator\Desktop\metanome\1\Metanome-master\frontend\src
[ERROR] module.js:478
[ERROR]     throw err;
[ERROR]     ^
[ERROR]
[ERROR] Error: Cannot find module 'C:\Users\Administrator\Desktop\metanome\1\Metanome-master\frontend\src\node_modules\bower\bin\bower'
[ERROR]     at Function.Module._resolveFilename (module.js:476:15)
[ERROR]     at Function.Module._load (module.js:424:25)
[ERROR]     at Module.runMain (module.js:611:10)
[ERROR]     at run (bootstrap_node.js:394:7)
[ERROR]     at startup (bootstrap_node.js:160:9)
[ERROR]     at bootstrap_node.js:507:3

I have install this project both in Ubuntu 18.04 and win10
