### ISSUE TITLE
AlgorithmExecution duplicates Algorithm database entries

### ISSUE THREAD

**Issue by saschahauke** [HPI-Information-Systems/Metanome#391]
In result of n Executions the backend holds n entries of the executed Algorithm under the same id.

`[...
{  
      "id":8,
      "fileName":"HyFD-1.1-SNAPSHOT.jar",
      "name":"HyFD-1.1-SNAPSHOT",
      "author":"Thorsten Papenbrock",
      "description":"Hybrid Sampling- and Lattice-Traversal-based FD discovery",
      "ind":false,
      "fd":true,
      "ucc":false,
      "cucc":false,
      "od":false,
      "mvd":false,
      "basicStat":false,
      "dc":false,
      "relationalInput":true,
      "databaseConnection":false,
      "tableInput":false,
      "fileInput":false
   },
   {  
      "id":8,
      "fileName":"HyFD-1.1-SNAPSHOT.jar",
      "name":"HyFD-1.1-SNAPSHOT",
      "author":"Thorsten Papenbrock",
      "description":"Hybrid Sampling- and Lattice-Traversal-based FD discovery",
      "ind":false,
      "fd":true,
      "ucc":false,
      "cucc":false,
      "od":false,
      "mvd":false,
      "basicStat":false,
      "dc":false,
      "relationalInput":true,
      "databaseConnection":false,
      "tableInput":false,
      "fileInput":false
   }
   ...
   ]`

**Comment by maxifischer** [comment]
Which part of Metanome do you refer to? Every algorithm from the algorithm overview has its unique algorithm ID that might be referred to by multiple executions that have a unique execution ID as well. Does this cause a particular issue for you?
