### ISSUE TITLE
bad relativepath in Metanome\testing_algorithms\*\pom.xml

### ISSUE THREAD

**Issue by PrimarDarren** [HPI-Information-Systems/Metanome#406]
Trying to do mvn -T 1C clean install

But mvn complaining about unable to resolve parent

Edited 14 pom.xml in folders under Metanome\testing_algorithms

i.e. Metanome\testing_algorithms\*\pom.xml

relativepath was ../../pom.xml

changed it to ../pom.xml 

mvn stopped complaining

**Comment by thorsten-papenbrock** [comment]
Many thanks for the bug report!

The path-issue somehow did not cause an error in our local environments.

We now fixed it.
