### ISSUE TITLE
Check for issues in current maven build

### ISSUE THREAD

**Issue by JoeAtHPI** [HPI-Information-Systems/Metanome#413]

**Comment by vmaharajh** [comment]
The first error I see is:

````
[ERROR]   The project de.metanome:backend:1.2-SNAPSHOT (C:\Users\vmaharajh\code\Metanome\backend\pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for com.sap.cloud.db.jdbc:ngdbc:jar is missing. @ line 242, column 21
````

To get past this error, I added the following into the `com.sap.cloud.db.jdbc` group of /backend/pom.xml:
````
<version>2.4.62</version>
````

However that then leads to another error
````
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.3:jar (default) on project test_helper: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in http://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
````

**Comment by JoeAtHPI** [comment]
Hey Maharajh,
thanks for bringing up this issue! The defect was behind the defined scope of the dependency in the root pom file. I just updated it to master so at least the first error should disappear. The second point is mentioned in our readme under dependencies, but I'll update it to make the needed version more clear since it can indeed be misunderstood :)
Sorry for the inconvenience! 
Cheers

**Comment by vmaharajh** [comment]
Thanks for fixing it! Yeah, I saw the directions in the README. Since it said "Java JDK 1.8 or later", I figured 13 would work.

**Comment by JoeAtHPI** [comment]
When you download a java version of your choice, there's a difference between the jdk1.x and the jdkx version. So "Java JDK 1.8 or later" actually refers to versions like jdk1.9, jdk1.10 and so on. The jdkxx versions are OpenJDKS. Maybe this link will bring some insights :) https://stackoverflow.com/questions/22358071/differences-between-oracle-jdk-and-openjdk

**Comment by vmaharajh** [comment]
Ah. Thanks for the explanation, that makes sense. I'm new to java, and trying to understand one of the metanome algorithms.
